### ISSUE TITLE
Add a Known Issues page

### ISSUE THREAD

**Issue by niden** [phalcon/phalcon.io#3]
Add highly visible known issues page to the website, separated by version. Something like
## 1.3.0.

no known issues
## 1.2.1.

Asset Manager sometimes generates empty file.
Asset Manager adds semicolons between files.
## 1.2.0.

Asset Manager sometimes generates empty file.
Asset Manager adds semicolons between files.

Etc.

If issue is opened for given bug, it should be linked to the entry on the page.

From: https://github.com/phalcon/website/issues/117 @swader

**Comment by Swader** [comment]
Wow, what a nostalgia injection :)
