### ISSUE TITLE
Wrong URL of "Get Phalcon" button on main page

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon.io#35]
![image](https://user-images.githubusercontent.com/3289702/71314941-38f54780-244a-11ea-9a73-7c6de1decd09.png)

* **Current:** https://docs.phalcon.io/latest/en-us/installation
* **Correct:** https://docs.phalcon.io/4.0/en/installation

**Comment by ruudboon** [comment]
Fixed with a redirect. Will move all docs to /lates soon.
