### ISSUE TITLE
Update downloads page for Phalcon 4.x

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/phalcon.io#4]
Add note about PSR extension.

Refs:
- https://github.com/phalcon/cphalcon/pull/13437
- https://github.com/phalcon/cphalcon/issues/13434

**Comment by ruudboon** [comment]
Let's update this when Pecl is done. We're even referring to Phalcon 1.0 :D

**Comment by niden** [comment]
Resolved this with https://github.com/phalcon/phalcon.io/commit/7e2a711aad15de2702bd6a6036031ab9c805b8ed
