### ISSUE TITLE
Pictures on mobile not round

### ISSUE THREAD

**Issue by ruudboon** [phalcon/phalcon.io#47]
On mobile our contributors images aren't fully round. Can we have a look at this?

<img width="549" alt="Screenshot 2020-02-01 at 08 10 26" src="https://user-images.githubusercontent.com/7444246/73588519-737ee500-44ca-11ea-9478-2d8266ea3a15.png">

**Comment by Arhell** [comment]
resolve, if after rebooting nothing has changed you need hard reload browser
